# Generated by Django 4.2.20 on 2025-05-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_rate', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('night_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
            ],
        ),
    ]
