# Generated by Django 4.2.20 on 2025-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=50, unique=True)),
                ('current_day_reading', models.IntegerField(default=0)),
                ('current_night_reading', models.IntegerField(default=0)),
            ],
        ),
    ]
